/// Flutter icons NexusFont
/// Copyright (C) 2026 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NexusFont
///      fonts:
///       - asset: fonts/NexusFont.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class NexusFont {
  NexusFont._();

  static const _kFontFam = 'NexusFont';
  static const String? _kFontPkg = null;

  static const IconData nexusLogo = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
