// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbClNGMV5GnMAM4f9OMW-j9IpN0ioTUts',
    appId: '1:1084705895690:web:5e9ec61bcb118312d736f3',
    messagingSenderId: '1084705895690',
    projectId: 'nexus-smart-center',
    authDomain: 'nexus-smart-center.firebaseapp.com',
    storageBucket: 'nexus-smart-center.firebasestorage.app',
    measurementId: 'G-6HDFDG69F4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_MminU_aqPZURGfqVE6IAFHhh5OSMZ-U',
    appId: '1:1084705895690:android:9f847c75136fba18d736f3',
    messagingSenderId: '1084705895690',
    projectId: 'nexus-smart-center',
    storageBucket: 'nexus-smart-center.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbBtjYiTvVyBhwO8yAszM91EO8zgBrolo',
    appId: '1:1084705895690:ios:3bfd2104ba9d4cebd736f3',
    messagingSenderId: '1084705895690',
    projectId: 'nexus-smart-center',
    storageBucket: 'nexus-smart-center.firebasestorage.app',
    iosBundleId: 'com.example.nexusSmartCenter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbBtjYiTvVyBhwO8yAszM91EO8zgBrolo',
    appId: '1:1084705895690:ios:3bfd2104ba9d4cebd736f3',
    messagingSenderId: '1084705895690',
    projectId: 'nexus-smart-center',
    storageBucket: 'nexus-smart-center.firebasestorage.app',
    iosBundleId: 'com.example.nexusSmartCenter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbClNGMV5GnMAM4f9OMW-j9IpN0ioTUts',
    appId: '1:1084705895690:web:248fa57d8eef782cd736f3',
    messagingSenderId: '1084705895690',
    projectId: 'nexus-smart-center',
    authDomain: 'nexus-smart-center.firebaseapp.com',
    storageBucket: 'nexus-smart-center.firebasestorage.app',
    measurementId: 'G-896J7WPQSZ',
  );
}
