/// Flutter icons UnenFont
/// Copyright (C) 2026 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  UnenFont
///      fonts:
///       - asset: fonts/UnenFont.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class UnenFont {
  UnenFont._();

  static const _kFontFam = 'UnenFont';
  static const String? _kFontPkg = null;

  static const IconData unenicon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
